### ISSUE TITLE
Does not work with refinerycms-core (3.0.0)  /  Rails 4

### ISSUE THREAD

**Issue by asgeo1** [refinery/refinerycms-search#45]
Can this plugin be updated to work with refinerycms-core (3.0.0)  /  Rails 4 ?

This guys seems to have done it: https://github.com/wantedtech/refinerycms-search

**Comment by jess** [comment]
@parndt is it possible to get search working with refinerycms master? I've used the above link, but doesn't see to be working consistently...I'm using translations and wondering if that is an issue.

**Comment by bricesanchez** [comment]
It's now fixed by @anitagraham with her PR #51. :)

**Comment by jess** [comment]
:+1:  :+1: thanks @anitagraham
