### ISSUE TITLE
Resave / Rebuild index

### ISSUE THREAD

**Issue by jess** [refinery/refinerycms-search#56]
I've removed my index (`rm -rf tmp/index`) and am trying to save all my pages as referenced in the [readme](https://github.com/refinery/refinerycms-search#re-save-all-records-that-have-not-been-indexed-before). Running 

```ruby
Refinery::Page.all(&:save)
```

Seems to work fine for the default translations, but not for any other translations being used. However, if I go to the refinery admin (/refinery) and navigate to a :es translated page and save it, it'll show up in the search results.

I've tried:

```ruby
Refinery::PagePart.all.map(&:save)
Refinery::PagePart::Translations.all.map(&:save)
```
But none seem to work. Is there a way in the console to force the index of the translated pages??

**Comment by bricesanchez** [comment]
Removing all tmp content and restarting the app works for me : `rm -rf tmp/`

**Comment by jess** [comment]
@bricesanchez are you using multiple translations?

**Comment by bricesanchez** [comment]
I use french and english content. `refinerycms-search` can search in current locale but not in another locale.

**Comment by jess** [comment]
maybe I needed to `rm -rf tmp/` instead of `rm -rf tmp/index'

I'll close the issue...sounds like something I did wrong. Thanks for the info.
