### ISSUE TITLE
No results for search in Russian

### ISSUE THREAD

**Issue by IvanVP** [refinery/refinerycms-search#57]
Hello.

Search in English works fine, but when I try to search russian words, I have no results.

**Comment by bricesanchez** [comment]
Do you try to search russian words when the site is in english ?

**Comment by simi** [comment]
@IvanVP multilingual search is not possible at this moment. Is that your problem?

*Anyone COD player?*

![maxresdefault](https://cloud.githubusercontent.com/assets/193936/7086163/ffce532c-df7d-11e4-80b0-f3a36206654c.jpg)

**Comment by bricesanchez** [comment]
Is @simi answer have explained your issue ?

**Comment by Elsant** [comment]
Hello,
Sorry for delay.
My i18n.rb looks like
  config.default_locale = :ru
  config.current_locale = :ru
  config.default_frontend_locale = :ru
  config.frontend_locales = [:ru]
  config.locales = {:ru=>"Русский"}

When I make new page with russian words - Refiinery:: Search shows no result
When I make page with english words - Search give exactly results.
I don't understand why?

**Comment by bricesanchez** [comment]
@Elsant Did you reindex the content ?

**Comment by Elsant** [comment]
No, but I made it from scratch  with PosgreSQL. 
I reindexed now all pages, even added new pages. It didn't work.
With settings above - english words are finding ok, but with russians words search gives "No results"

**Comment by bricesanchez** [comment]
This is the same error as #61 and #62. I close this issue, there will be a PR soon.
