### ISSUE TITLE
Porblems - search page content

### ISSUE THREAD

**Issue by mrjumpy** [refinery/refinerycms-search#61]
Hi
I can search page title, but I can search page content.
How should  I do?
Or
there is docs I can follow up?
Thank You!!

**Comment by mrjumpy** [comment]
Yes, I find the solution.
But, when I using "Chinese words" search(zh-TW).
There's no result.
Is this a issue?
or this plugin only support english words?

**Comment by bricesanchez** [comment]
It's probably the same error than #57, i'm confused.

**Comment by bricesanchez** [comment]
There is a way to find a solution : https://github.com/dougal/acts_as_indexed/issues/37

**Comment by mrjumpy** [comment]
I've tried. But it's not work.
I think maybe just as same as #57 
any idea?

**Comment by bricesanchez** [comment]
I'm working on a fix with this branch : https://github.com/refinery/refinerycms-search/tree/fix-unicode
