### ISSUE TITLE
Please add a "source code" link to your rubygems page

### ISSUE THREAD

**Issue by jaredbeck** [refinery/refinerycms-search#65]
I couldn't find a link from your rubygems page (https://rubygems.org/gems/refinerycms-search) to your github repo. Rubygems provides a field for this in your gem profile.

Thanks!

**Comment by parndt** [comment]
@jaredbeck could you add this for us and send a pull request please?

**Comment by bricesanchez** [comment]
@parndt I think, you have to add it in Rubygems directly : https://www.bountysource.com/issues/1429059-please-add-source-code-link-to-https-rubygems-org-gems-eventmachine

**Comment by simi** [comment]
@parndt https://rubygems.org/gems/refinerycms-search/edit

**Comment by parndt** [comment]
Huh today I learned.

Thanks, done!

**Comment by jaredbeck** [comment]
Yeah, it's weird. You'd think it would be in your gemspec.  ¯\_(ツ)_/¯
