### ISSUE TITLE
search with chinese not work

### ISSUE THREAD

**Issue by oolzpishere** [refinery/refinerycms-search#68]
Hi,

I'm search at admin/pages with chinese, don't have any results when the title exactly the same.

![sflx refinery](https://cloud.githubusercontent.com/assets/11001753/18721559/9e28929e-8063-11e6-96ac-d4884f7478e4.png)

I capture the search result page and print the params below. Params[:search] not change to ascii.

gem 'refinerycms', '~> 3.0'
gem 'refinerycms-acts-as-indexed', '~> 3.0'
gem 'refinerycms-search', github: 'refinery/refinerycms-search', branch: 'master'

**Comment by bricesanchez** [comment]
Hi, 

Could you try this PR : 
https://github.com/refinery/refinerycms-search/pull/64

**Comment by oolzpishere** [comment]
@bricesanchez thank you.
Follow your commit, works fine now : ) 
[https://github.com/refinery/refinerycms-search/pull/64/commits/8d5e4fde67f0137b27a75e7df0e168a58d551820](url)

**Comment by oolzpishere** [comment]
@bricesanchez 
Hi, 
I try to figure out how the search work at admin page for couple hours.
Still don't know the process.
It's look like not use the refinerycms-search engine at the page management.
How the `@pages ` get filtered pages from search submit.
It's there any short answer? 
Thanks

**Comment by bricesanchez** [comment]
All the logic stands in https://github.com/refinery/refinerycms-acts-as-indexed
